services:
  client:
    build: ./client
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build: ./server
    restart: always
    ports:
      - 8060:8060
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - START_MODE=cluster # or cluster

volumes:
  video-editing-app:
